"""update column name

Revision ID: 78278db4d3b9
Revises: aa5e90e10ab9
Create Date: 2025-06-21 08:43:41.007028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78278db4d3b9'
down_revision: Union[str, Sequence[str], None] = 'aa5e90e10ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_categories_title'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.drop_column('categories', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_title'), 'categories', ['title'], unique=False)
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
