"""add foreign key, index

Revision ID: a78094d90202
Revises: 9fc41fe73d5a
Create Date: 2025-06-21 08:13:43.977422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78094d90202'
down_revision: Union[str, Sequence[str], None] = '9fc41fe73d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    # ### end Alembic commands ###
