"""add index

Revision ID: aa5e90e10ab9
Revises: a78094d90202
Create Date: 2025-06-21 08:14:36.765163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5e90e10ab9'
down_revision: Union[str, Sequence[str], None] = 'a78094d90202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_title'), 'categories', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_title'), table_name='categories')
    # ### end Alembic commands ###
